sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: J/OmDiqVVAnf+k4SSuM0AXHjAU5WAnP+JbLJRDKz7UdtH8XXuNZ1R9jMOffHv1vl6eoG8RRROpFFxxiKPTbGuo3rLXk/JTX/xyFQnRMWUFJJ/6EYzGP1YrM0yghEc/JK6Nwc9/Gu6+udyixf7znlalyJ5zgHkvcRPBnYMy6nSpr1nK946UK3cLT+jVmFV9Ntsf8m15qw8uwfWLqddPfrBzPMRajYGnbjgGbI/HlSaxqyp1Pe+1ngf6jlnCOMHdoc00H67LJUObxbg5Z7qCiM4QzXz8FCnOQv7xLom7dt4YIe1b0DIipgEsh2FfkPeEPQaZd2EUAamh2Fc56CAYSZ84FVfhcJCwDy9bgW8ByISCzq/7FlsukxLsiYMuOML9QKeLzUJK1DkxmGQgqSCanJDotxQVzGzcL1xxb98Q4D495uUX/kT324jy3mMictHBEp265hlpPJaSCpQHsDF/eGpbB032bYFtwX/z6cLJOoXjCKL8icCT3IQR+ay1rmpO/hbxMO1rjQOLYmLCdD8MJk9X15+u7XhtZpKDziNVZOE5hd87QLUeV+FQGfMHHhkUlHegY51M/kdXKDt+KicPfnJ9lq8I+trsuUHxFVciiJMWNHlky/3rprSzAvFpcdDuukEgTfLAevmvlgkskJJvskXHmAGPa62j2bKGaMsYj4SUI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Diary-of-Samuel-Pepys---Volume-54--June-1667_4177
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy